// harness adapters — one thin stage per harness, dispatched from compile over the same
// compiled entries. the superpowers lesson, kept deliberately: CONTENT NEVER FORKS PER
// HARNESS — skills copy verbatim (+stamp), every root file gets the same managed
// orientation block; only the injection points differ per harness:
//   claude-code → .claude/{skills,agents,commands} + CLAUDE.md block  (native everything)
//   codex       → AGENTS.md block + .agents/skills mirror             (~/.codex reads AGENTS.md)
//   pi          → AGENTS.md block + .agents/skills mirror             (pi auto-discovers .agents/skills)
//   cursor      → .cursor/rules/dreamteamer.mdc + .agents/skills      (.mdc is cursor's native rule file)
//   gemini-cli  → GEMINI.md block + .agents/skills mirror             (GEMINI.md is its context file)
// managed blocks live in USER-OWNED files (committed); generated dirs (.claude, .agents,
// .cursor) are gitignored and pruned by stamp. removing a harness from config removes its
// block/file on the next compile.
import fs from 'node:fs';
import path from 'node:path';
import { load, dump } from './yaml.js';

export const KNOWN_HARNESSES = ['claude-code', 'codex', 'pi', 'gemini-cli', 'cursor'];

export const STAMP = '<!-- generated by dreamteamer compile — do not edit; source of truth lives in modules/*/system -->';

const BEGIN = '<!-- dreamteamer:begin (generated — do not edit inside this block) -->';
const END = '<!-- dreamteamer:end -->';

export function runHarnessAdapters({ root, entries, harnesses, prevManifest }) {
	const outputs = [];
	const summary = [];
	const rel = (p) => path.relative(root, p);
	const write = (out, bytes) => {
		const dest = path.join(root, out);
		fs.mkdirSync(path.dirname(dest), { recursive: true });
		fs.writeFileSync(dest, bytes);
		outputs.push(out);
	};

	for (const h of harnesses) {
		if (!KNOWN_HARNESSES.includes(h)) console.warn(`⚠ unknown harness "${h}" in dreamteamer.harnesses — skipped (known: ${KNOWN_HARNESSES.join(', ')})`);
	}
	const on = (h) => harnesses.includes(h);
	const skillsIndex = buildSkillsIndex(entries);

	// ---- claude-code: native skills/agents/commands dirs + CLAUDE.md block ----------
	if (on('claude-code')) {
		let n = 0;
		for (const [rt, e] of entries) {
			if (rt.startsWith('system/skills/')) {
				const out = path.join('.claude/skills', rt.slice('system/skills/'.length));
				write(out, out.endsWith('.md') ? stampMd(e.bytes) : e.bytes);
				n++;
			} else if (rt.startsWith('system/agents/')) {
				write(path.join('.claude/agents', path.basename(rt).replace(/\.agent\.md$/, '.md')), stampMd(transformAgent(e.bytes)));
				n++;
			} else if (rt.startsWith('system/commands/')) {
				write(path.join('.claude/commands', path.basename(rt).replace(/\.command\.md$/, '.md')), stampMd(e.bytes));
				n++;
			}
		}
		summary.push(`claude-code → .claude (${n} files)`);
	}
	writeBlock(root, 'CLAUDE.md', on('claude-code') ? orientationBlock('claude-code', skillsIndex) : null);

	// ---- shared cross-agent skills mirror (.agents/skills) — codex/pi discover it,
	// cursor/gemini blocks point at it. written once no matter how many harnesses use it.
	const wantsMirror = on('codex') || on('pi') || on('cursor') || on('gemini-cli');
	if (wantsMirror) {
		let n = 0;
		for (const [rt, e] of entries) {
			if (!rt.startsWith('system/skills/')) continue;
			const out = path.join('.agents/skills', rt.slice('system/skills/'.length));
			write(out, out.endsWith('.md') ? stampMd(e.bytes) : e.bytes);
			n++;
		}
		summary.push(`.agents/skills mirror (${n} files)`);
	}

	// ---- codex + pi: both read root AGENTS.md; one block serves both ----------------
	writeBlock(root, 'AGENTS.md', on('codex') || on('pi') ? orientationBlock('agents-md', skillsIndex) : null);
	if (on('codex')) summary.push('codex → AGENTS.md block');
	if (on('pi')) summary.push('pi → AGENTS.md block + .agents/skills');

	// ---- gemini-cli: GEMINI.md is its context file -----------------------------------
	writeBlock(root, 'GEMINI.md', on('gemini-cli') ? orientationBlock('gemini', skillsIndex) : null);
	if (on('gemini-cli')) summary.push('gemini-cli → GEMINI.md block');

	// ---- cursor: native .mdc rule (alwaysApply) ---------------------------------------
	if (on('cursor')) {
		const mdc = `---\ndescription: dreamteamer workspace orientation (generated)\nalwaysApply: true\n---\n\n${orientationBlock('cursor', skillsIndex)}\n\n${STAMP}\n`;
		write('.cursor/rules/dreamteamer.mdc', Buffer.from(mdc));
		summary.push('cursor → .cursor/rules/dreamteamer.mdc');
	}

	// ---- prune: anything WE stamped that this compile didn't produce ------------------
	const current = new Set(outputs);
	for (const dir of ['.claude/skills', '.claude/agents', '.claude/commands', '.agents/skills', '.cursor/rules']) {
		const abs = path.join(root, dir);
		if (!fs.existsSync(abs)) continue;
		for (const f of walk(abs)) {
			const relOut = rel(f);
			if (current.has(relOut)) continue;
			if (/\.(md|mdc)$/.test(f) && fs.readFileSync(f, 'utf8').includes(STAMP)) fs.rmSync(f);
		}
	}
	for (const old of prevManifest?.['adapter-outputs'] ?? []) {
		if (!current.has(old) && fs.existsSync(path.join(root, old))) fs.rmSync(path.join(root, old));
	}
	// pruning leaves empty skill folders behind — sweep them (and the roots when hollow)
	for (const dir of ['.claude', '.agents', '.cursor']) pruneEmptyDirs(path.join(root, dir));

	return { outputs, summary };
}

// skill id → description one-liners from each SKILL.md's frontmatter; the orientation
// block carries this index so harnesses without native skill discovery still get triggers.
function buildSkillsIndex(entries) {
	const index = [];
	for (const [rt, e] of entries) {
		const m = /^system\/skills\/([^/]+)\/SKILL\.md$/.exec(rt);
		if (!m) continue;
		const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(e.bytes.toString('utf8'));
		let desc = '';
		try { desc = (fm ? load(fm[1]) : {})?.description ?? ''; } catch { /* unparseable frontmatter */ }
		index.push({ id: m[1], desc: String(desc).replace(/\s+/g, ' ').trim() });
	}
	return index.sort((a, b) => a.id.localeCompare(b.id));
}

function orientationBlock(flavor, skillsIndex) {
	const lines = [
		'this workspace is operated by dreamteamer v0.6. **read the `using-dreamteamer` skill before',
		'working with data.** schemas (read): `.dreamteamer/system/collections/` (provenance:',
		'`.dreamteamer/manifest.yaml`). sources (write): module `system/` folders (see manifest for',
		'channels). data: `data/`; operational records: `state/`. records are `<id>.<suffix>.<ext>`',
		'files; ids are paths; references are `<collection>/<id>`. run `dreamteamer check` (`npm run',
		'check`) after bulk edits; run `dreamteamer compile` (`npm run compile`) after changing any',
		'source or installing modules.',
	];
	// claude-code discovers skills natively (Skill tool) — an index in CLAUDE.md is pure
	// context bloat there. every other harness gets the trigger index + discovery pointers.
	if (flavor !== 'claude-code') {
		lines.push(
			'',
			"skills — reusable techniques, one folder per skill at `.agents/skills/` (canonical:",
			"`.dreamteamer/system/skills/`); each SKILL.md's description says when to load it. load",
			'the relevant skill BEFORE the task:',
			...skillsIndex.map((s) => `- \`${s.id}\` — ${s.desc}`),
			'',
			'agent personas live at `.dreamteamer/system/agents/*.agent.md`; commands at',
			'`.dreamteamer/system/commands/` (invoked as `/<name>` by the harness).',
		);
	}
	return lines.join('\n');
}

// managed block in a USER-OWNED root file. content=null removes the block; a file left
// empty (or whitespace) after removal is deleted — we created it, we clean it up.
function writeBlock(root, filename, content) {
	const file = path.join(root, filename);
	const exists = fs.existsSync(file);
	if (content == null) {
		if (!exists) return;
		let text = fs.readFileSync(file, 'utf8');
		if (!text.includes(BEGIN)) return;
		text = text.replace(new RegExp(`\\n?\\n?${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n?`), '\n');
		if (text.trim() === '') fs.rmSync(file);
		else fs.writeFileSync(file, text);
		return;
	}
	const block = `${BEGIN}\n${content}\n${END}`;
	let text = exists ? fs.readFileSync(file, 'utf8') : '';
	if (text.includes(BEGIN)) text = text.replace(new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`), block);
	else text = (text.trimEnd() + '\n\n' + block + '\n').replace(/^\n+/, '');
	fs.writeFileSync(file, text);
}

export function stampMd(bytes) {
	const text = bytes.toString('utf8');
	return text.includes(STAMP) ? bytes : Buffer.from(text.trimEnd() + '\n\n' + STAMP + '\n');
}

// dreamteamer agent record -> claude-code subagent: `skills` is not a harness
// frontmatter key; translate it into a binding instruction in the body.
export function transformAgent(bytes) {
	const text = bytes.toString('utf8');
	const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
	if (!m) return bytes;
	const doc = load(m[1]) ?? {};
	const body = text.slice(m[0].length);
	const skills = doc.skills ?? [];
	delete doc.skills;
	const skillLine = skills.length
		? `ALWAYS load these skills (Skill tool) before acting: ${skills.map((s) => String(s).replace(/^skills\//, '')).join(', ')}.\n\n`
		: '';
	return Buffer.from(`---\n${dump(doc)}---\n\n${skillLine}${body.trimStart()}`);
}

function escapeRe(s) {
	return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// depth-first removal of empty directories; returns true when `dir` itself was removed.
// dotfile-only dirs count as non-empty (never delete something we can't see into).
function pruneEmptyDirs(dir) {
	if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return false;
	for (const name of fs.readdirSync(dir)) {
		const p = path.join(dir, name);
		if (fs.statSync(p).isDirectory()) pruneEmptyDirs(p);
	}
	if (fs.readdirSync(dir).length === 0) {
		fs.rmdirSync(dir);
		return true;
	}
	return false;
}

function* walk(dir) {
	for (const name of fs.readdirSync(dir).sort()) {
		if (name.startsWith('.')) continue;
		const p = path.join(dir, name);
		if (fs.statSync(p).isDirectory()) yield* walk(p);
		else yield p;
	}
}
