// harness adapters — one thin stage per harness, dispatched from compile over the same
// compiled entries. the superpowers lesson, kept deliberately: CONTENT NEVER FORKS PER
// HARNESS — skills copy verbatim (+stamp), every root file gets the same managed
// orientation block; only the injection points differ per harness:
//   claude-code → .claude/{skills,agents,commands} + CLAUDE.md block  (native everything)
//   codex       → AGENTS.md block + .agents/skills mirror             (~/.codex reads AGENTS.md)
//   pi          → AGENTS.md block + .agents/skills mirror             (pi auto-discovers .agents/skills)
//   cursor      → .cursor/rules/dreamteamer.mdc + .agents/skills      (.mdc is cursor's native rule file)
//   gemini-cli  → GEMINI.md block + .agents/skills mirror             (GEMINI.md is its context file)
// managed blocks live in USER-OWNED files (committed); generated dirs (.claude, .agents,
// .cursor) are gitignored and pruned by stamp. removing a harness from config removes its
// block/file on the next compile.
import fs from 'node:fs';
import path from 'node:path';
import { load, dump } from './yaml.js';

export const KNOWN_HARNESSES = ['claude-code', 'codex', 'pi', 'gemini-cli', 'cursor'];

export const STAMP = '<!-- generated by dreamteamer compile — do not edit; source of truth lives in modules/<module>/<kind>/ -->';

const BEGIN = '<!-- dreamteamer:begin (generated — do not edit inside this block) -->';
const END = '<!-- dreamteamer:end -->';

export function runHarnessAdapters({ root, entries, harnesses, prevManifest, sourceLayout = 'flat', namespaces = [], version = 'unknown', workspaceModule = '' }) {
	const outputs = [];
	// ⚠ SEPARATE from `outputs`: these are USER-OWNED root files carrying a managed block, and the
	// prune loop below DELETES anything in a previous manifest's `adapter-outputs` that this compile
	// did not produce — listing CLAUDE.md there would delete the operator's own instructions the day
	// a harness is switched off. They are reported so a schema write can COMMIT the regenerated block
	// beside the source it changed (schema-ops.regeneratedOutputs), which is the only other reader.
	const blocks = [];
	const summary = [];
	const rel = (p) => path.relative(root, p);
	const block = (file, content) => { writeBlock(root, file, content); if (content != null) blocks.push(file); };
	const write = (out, bytes) => {
		const dest = path.join(root, out);
		fs.mkdirSync(path.dirname(dest), { recursive: true });
		fs.writeFileSync(dest, bytes);
		outputs.push(out);
	};

	for (const h of harnesses) {
		if (!KNOWN_HARNESSES.includes(h)) console.warn(`⚠ unknown harness "${h}" in dreamteamer.harnesses — skipped (known: ${KNOWN_HARNESSES.join(', ')})`);
	}
	const on = (h) => harnesses.includes(h);
	const skillsIndex = buildSkillsIndex(entries);

	// ---- claude-code: native skills/agents/commands dirs + CLAUDE.md block ----------
	if (on('claude-code')) {
		let n = 0;
		for (const [rt, e] of entries) {
			if (rt.startsWith('skills/')) {
				const out = path.join('.claude/skills', rt.slice('skills/'.length));
				write(out, out.endsWith('.md') ? stampMd(e.bytes) : e.bytes);
				n++;
			} else if (rt.startsWith('agents/')) {
				write(path.join('.claude/agents', path.basename(rt).replace(/\.agent\.md$/, '.md')), stampMd(transformAgent(e.bytes)));
				n++;
			} else if (rt.startsWith('commands/')) {
				write(path.join('.claude/commands', path.basename(rt).replace(/\.command\.md$/, '.md')), stampMd(e.bytes));
				n++;
			}
		}
		summary.push(`claude-code → .claude (${n} files)`);
	}
	block('CLAUDE.md', on('claude-code') ? orientationBlock('claude-code', skillsIndex, sourceLayout, namespaces, version, entries, workspaceModule) : null);

	// ---- shared cross-agent skills mirror (.agents/skills) — codex/pi discover it,
	// cursor/gemini blocks point at it. written once no matter how many harnesses use it.
	const wantsMirror = on('codex') || on('pi') || on('cursor') || on('gemini-cli');
	if (wantsMirror) {
		let n = 0;
		for (const [rt, e] of entries) {
			if (!rt.startsWith('skills/')) continue;
			const out = path.join('.agents/skills', rt.slice('skills/'.length));
			write(out, out.endsWith('.md') ? stampMd(e.bytes) : e.bytes);
			n++;
		}
		summary.push(`.agents/skills mirror (${n} files)`);
	}

	// ---- codex + pi: both read root AGENTS.md; one block serves both ----------------
	block('AGENTS.md', on('codex') || on('pi') ? orientationBlock('agents-md', skillsIndex, sourceLayout, namespaces, version, entries, workspaceModule) : null);
	if (on('codex')) summary.push('codex → AGENTS.md block');
	if (on('pi')) summary.push('pi → AGENTS.md block + .agents/skills');

	// ---- gemini-cli: GEMINI.md is its context file -----------------------------------
	block('GEMINI.md', on('gemini-cli') ? orientationBlock('gemini', skillsIndex, sourceLayout, namespaces, version, entries, workspaceModule) : null);
	if (on('gemini-cli')) summary.push('gemini-cli → GEMINI.md block');

	// ---- cursor: native .mdc rule (alwaysApply) ---------------------------------------
	if (on('cursor')) {
		const mdc = `---\ndescription: dreamteamer workspace orientation (generated)\nalwaysApply: true\n---\n\n${orientationBlock('cursor', skillsIndex, sourceLayout, namespaces, version, entries, workspaceModule)}\n\n${STAMP}\n`;
		write('.cursor/rules/dreamteamer.mdc', Buffer.from(mdc));
		summary.push('cursor → .cursor/rules/dreamteamer.mdc');
	}

	// ---- prune: anything WE stamped that this compile didn't produce ------------------
	const current = new Set(outputs);
	for (const dir of ['.claude/skills', '.claude/agents', '.claude/commands', '.agents/skills', '.cursor/rules']) {
		const abs = path.join(root, dir);
		if (!fs.existsSync(abs)) continue;
		for (const f of walk(abs)) {
			const relOut = rel(f);
			if (current.has(relOut)) continue;
			if (/\.(md|mdc)$/.test(f) && fs.readFileSync(f, 'utf8').includes(STAMP)) fs.rmSync(f);
		}
	}
	for (const old of prevManifest?.['adapter-outputs'] ?? []) {
		if (!current.has(old) && fs.existsSync(path.join(root, old))) fs.rmSync(path.join(root, old));
	}
	// pruning leaves empty skill folders behind — sweep them (and the roots when hollow)
	for (const dir of ['.claude', '.agents', '.cursor']) pruneEmptyDirs(path.join(root, dir));

	return { outputs, blocks, summary };
}

// skill id → description one-liners from each SKILL.md's frontmatter; the orientation
// block carries this index so harnesses without native skill discovery still get triggers.
function buildSkillsIndex(entries) {
	const index = [];
	for (const [rt, e] of entries) {
		const m = /^skills\/([^/]+)\/SKILL\.md$/.exec(rt);
		if (!m) continue;
		const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(e.bytes.toString('utf8'));
		let desc = '';
		try { desc = (fm ? load(fm[1]) : {})?.description ?? ''; } catch { /* unparseable frontmatter */ }
		index.push({ id: m[1], desc: String(desc).replace(/\s+/g, ' ').trim() });
	}
	return index.sort((a, b) => a.id.localeCompare(b.id));
}

/** One flattened line of prose from a possibly-folded YAML scalar. */
const flat = (s) => String(s ?? '').replace(/\s+/g, ' ').trim();

/** collection name -> description / use_when / whether it is a schema-ops collection, read from the
 *  compiled descriptor BYTES compile already holds. Same pattern as buildSkillsIndex: no filesystem
 *  read, and deliberately nothing that touches `data/` — see collectionsSection for why. */
function buildCollectionsIndex(entries) {
	const index = [];
	for (const [rt, e] of entries) {
		const m = /^collections\/(.+)\.collection\.yaml$/.exec(rt);
		if (!m) continue;
		let d = {};
		try { d = load(e.bytes.toString('utf8')) ?? {}; } catch { /* unparseable descriptor */ }
		index.push({
			name: d.name ?? m[1],
			// DERIVED, never a hardcoded name list: `runtime` is exactly the schema-ops set
			// (collections, commands, skills, agents, ui-views, command-bindings,
			// collection-templates, modules) and stays right in a workspace shipping others.
			system: d.storage?.base === 'runtime',
			description: flat(d.description),
			useWhen: flat(d.use_when),
			module: d.module ?? '',
			write: writeLine(d.schema),
		});
	}
	return index.sort((a, b) => a.name.localeCompare(b.name));
}

/** What can REFUSE a write, in one clause — nothing else about the fields. Required fields with no
 *  default (the CLI materializes defaults, so those never refuse), closed enums with their size, and
 *  the first `examples:` value where one is authored. A blind session's plan was correct until its
 *  first `dt add`, which the store refused on a 100-value enum and a required field the block never
 *  showed; the descriptor stays the authority, this is the line that keeps the first write from
 *  bouncing. Empty string when there is nothing that refuses. */
function writeLine(schema) {
	const props = schema?.properties ?? {};
	const required = (schema?.required ?? []).filter((f) => props[f] && props[f].default === undefined);
	const enums = Object.entries(props).flatMap(([f, p]) => { const e = p?.enum ?? p?.items?.enum; return Array.isArray(e) && e.length ? [`${f} enum(${e.length})`] : []; });
	const egs = Object.entries(props).flatMap(([f, p]) => Array.isArray(p?.examples) && p.examples.length ? [`${f}='${p.examples[0]}'`] : []);
	const parts = [...(required.length ? [`required ${required.join(' · ')}`] : []), ...(enums.length ? [enums.join(' · ')] : []), ...(egs.length ? [`e.g. ${egs.join(', ')}`] : [])];
	return parts.join('; ');
}

/** module id -> title / description / namespaces / source path, plus the skills and commands whose
 *  SOURCE lives under that path — read from the module records compile projected, never from
 *  package.json again. A skill or command belongs to the module with the longest source-path prefix;
 *  the root layout (`path: .`) is the empty prefix and so matches last. */
function buildModulesIndex(entries) {
	const mods = [];
	for (const [rt, e] of entries) {
		const m = /^modules\/(.+)\.module\.yaml$/.exec(rt);
		if (!m) continue;
		let d = {};
		try { d = load(e.bytes.toString('utf8')) ?? {}; } catch { /* unparseable record */ }
		const p = !d.path || d.path === '.' ? '' : `${d.path}/`;
		mods.push({ id: m[1], title: d.title ?? m[1], description: flat(d.description), namespaces: d.namespaces ?? [], path: p, bin: d.bin ?? [], skills: [], commands: [] });
	}
	mods.sort((a, b) => b.path.length - a.path.length); // longest prefix first
	for (const [rt, e] of entries) {
		const kind = /^skills\/([^/]+)\/SKILL\.md$/.exec(rt) ? 'skills' : /^commands\/(.+)\.command\.md$/.exec(rt) ? 'commands' : null;
		if (!kind) continue;
		const src = e.sources?.[0]?.path ?? '';
		const owner = mods.find((mod) => src.startsWith(mod.path));
		if (owner) owner[kind].push(kind === 'skills' ? rt.split('/')[1] : path.basename(rt).replace(/\.command\.md$/, ''));
	}
	for (const mod of mods) { mod.skills.sort(); mod.commands.sort(); }
	return mods;
}

/** Commands, for the harnesses that do NOT discover them natively. claude-code writes every command
 *  into `.claude/commands` and its harness injects name+description at session start, so an index in
 *  CLAUDE.md would be a second copy of what is already there. codex/pi/gemini-cli/cursor got one
 *  pointer line and nothing else — which is why this is conditional, like the skills index. */
function buildCommandsIndex(entries) {
	const index = [];
	for (const [rt, e] of entries) {
		const m = /^commands\/(.+)\.command\.md$/.exec(rt);
		if (!m) continue;
		const fm = /^---\r?\n([\s\S]*?)\r?\n---/.exec(e.bytes.toString('utf8'));
		let desc = '';
		try { desc = (fm ? load(fm[1]) : {})?.description ?? ''; } catch { /* unparseable frontmatter */ }
		index.push({ id: m[1], desc: flat(desc) });
	}
	return index.sort((a, b) => a.id.localeCompare(b.id));
}

/** THE LEXICON — the half of the DSL that was never at t=0. The grammar (record shape, reference
 *  shape, namespaces) has been in this block since 0.6; an agent could form a well-shaped reference
 *  and not name one thing it could be about. The dogfood vault's hand-written list in CLAUDE.md is
 *  the argument for deriving it: that list named three collections for 48 hours after they were
 *  deleted, because a human had to remember to edit it.
 *
 *  ⚠ NO RECORD COUNTS, and that is not an omission. This block lands in CLAUDE.md / AGENTS.md /
 *  GEMINI.md, which are COMMITTED files. A count changes on every write, so every compile after
 *  ordinary data work would re-dirty three tracked files — in trees where more than one agent has
 *  uncommitted work — and the number would be stale the moment it was printed. Ordering is
 *  module-grouped then alphabetical precisely so the block diffs ONLY when the schema changed.
 *
 *  GROUPED BY MODULE, the workspace's own first. A module is the one entity that answers "what is
 *  this AREA of the workspace for" — its sentence heads the group, its namespaces, skills and
 *  commands ride on the line below it, and its collections follow. Before this the block listed
 *  nouns by namespace and the reader had to infer the domains from the prefixes; the hand-written
 *  module table one dogfood workspace kept to fill that gap was the same failure the collection list
 *  had already been through. A module whose every collection is system-stored (the engine) is not a
 *  domain and gets no group; a skills-only module is one and does. */
function collectionsSection(index, modules, workspaceModule) {
	if (!index.length) return [];
	const lines = [
		'',
		'MODULES AND THEIR COLLECTIONS — what this workspace is for, one area at a time. A module ships',
		'one domain: its collections (the nouns), and the skills and commands that operate on them —',
		'read its skills before working in its area. The descriptor at',
		'`.dreamteamer/collections/<name>.collection.yaml` is the authority on fields, id shape and',
		'defaults — read it before writing a kind you have not written this session. Create records',
		'with `dt add <collection>`: it generates the id and rejects invalid writes before disk. A',
		'collection\'s `write:` line names only what the store REFUSES — required fields that have no',
		'default (a defaulted one is filled in for you), closed enums with their size, one example.',
	];
	const data = index.filter((c) => !c.system);
	const isWs = (m) => m.path === `modules/${workspaceModule}/`;
	const groups = modules
		.filter((m) => { const own = index.filter((c) => c.module === m.id); return own.some((c) => !c.system) || (!own.length && (m.skills.length || m.commands.length || m.bin.length)); })
		.sort((a, b) => (isWs(b) - isWs(a)) || a.title.localeCompare(b.title));
	for (const m of groups) {
		const where = [`\`${m.id}\``, m.path ? m.path.replace(/\/$/, '') : 'the workspace root', ...(m.namespaces.length ? [`namespaces: ${m.namespaces.join(' · ')}`] : [])];
		lines.push('', `**${m.title}** (${where.join(' · ')})${m.description ? ` — ${m.description}` : ''}`);
		const ships = [...(m.skills.length ? [`skills: ${m.skills.join(' · ')}`] : []), ...(m.commands.length ? [`commands: ${m.commands.map((c) => `/${c}`).join(' · ')}`] : []), ...(m.bin.length ? [`runs: ${m.bin.join(' · ')}`] : [])];
		if (ships.length) lines.push(`  ${ships.join(' · ')}`);
		for (const c of data.filter((c) => c.module === m.id)) {
			lines.push(`- ${c.name}${c.description ? ` — ${c.description}` : ''}`);
			if (c.useWhen) lines.push(`    use when: ${c.useWhen}`);
			if (c.write) lines.push(`    write: ${c.write}`);
		}
	}
	const system = index.filter((c) => c.system).map((c) => c.name);
	// ⚠ THIS LINE IS THE FIRST THING A SESSION READS about the system collections, and until 0.19.0
	// it said "schema-ops only", which named an internal module and a grammar that no longer exists.
	// It now names the VERBS and the one policy difference, because an agent that knows the verbs
	// exist still has to be told that these commit and records do not.
	if (system.length) {
		lines.push('', `- system collections — the SAME verbs (add · set · rm · rename · list · get), plus \`dt add-field\`/\`update-field\`/\`remove-field\`/\`rename-field <collection>\`. A system write COMMITS ITSELF, in the repo holding the source; a record write does not (\`dt commit\` publishes). Never hand-edit \`.dreamteamer/\` — it is build output: ${system.join(' · ')}`);
	}
	return lines;
}

/** Collection-templates are field sets modules stamp onto their collections — the provenance quad
 *  reaches ~40 collections in the dogfood vault and was stated nowhere an agent reads.
 *
 *  ⚠ RENDERED, NEVER HARDCODED. An earlier draft wrote the four provenance field names straight
 *  into this file. That is recipe knowledge in core: `provenance` is shipped by a MODULE, and
 *  deliberately triplicated (`provenance`, `crm-provenance`, `rnd-provenance`) so each module stays
 *  copyable on its own. A workspace without them would have been handed a block that lies. Core
 *  renders the line; the module owns the sentence. */
function templatesSection(entries) {
	const rows = [];
	for (const [rt, e] of entries) {
		const m = /^collection-templates\/(.+)\.collection-template\.yaml$/.exec(rt);
		if (!m) continue;
		let d = {};
		try { d = load(e.bytes.toString('utf8')) ?? {}; } catch { /* unparseable template */ }
		rows.push({ name: d.name ?? m[1], description: flat(d.description) });
	}
	if (!rows.length) return [];
	rows.sort((a, b) => a.name.localeCompare(b.name));
	return ['', 'CROSS-CUTTING TEMPLATES — field sets modules stamp onto their collections:',
		...rows.map((r) => `- ${r.name}${r.description ? ` — ${r.description}` : ''}`)];
}

/** `can-enter` / `can-exit` rendered LITERALLY. Translating a filter into English would be a
 *  generator that has to grow with every operator the filter grammar gains, for prose the binding's
 *  own `description:` already carries. Real shapes are a nested map terminating in one `_op`:
 *    {status: {_eq: draft}}          -> status=draft
 *    {status: {_in: [enriched, x]}}  -> status in enriched|x
 *    {file: {_nempty: true}}         -> file set
 *    {meeting: {_empty: true}}       -> meeting empty */
const GATE_OPS = {
	_eq: (p, v) => `${p}=${v}`,
	_in: (p, v) => `${p} in ${[].concat(v).join('|')}`,
	_nempty: (p) => `${p} set`,
	_empty: (p) => `${p} empty`,
};

function renderGate(label, filter) {
	const parts = [];
	const walkFilter = (obj, at) => {
		for (const [k, v] of Object.entries(obj ?? {})) {
			if (k.startsWith('_')) parts.push((GATE_OPS[k] ?? ((p, x) => `${p} ${k.slice(1)} ${x}`))(at, v));
			else if (v && typeof v === 'object') walkFilter(v, at ? `${at}.${k}` : k);
			else parts.push(`${at ? `${at}.` : ''}${k}=${v}`);
		}
	};
	if (filter && typeof filter === 'object') walkFilter(filter, '');
	return parts.length ? `${label}: ${parts.join(', ')}` : '';
}

/** The METHODS on a type. A binding says which collection a command applies to and the record state
 *  that makes it available — invisible on EVERY harness, claude-code included, whose native command
 *  discovery gives the command's description and nothing about what it acts on. The cost of the
 *  absence is on disk: a contact record in the dogfood vault carries the hand-written sentence
 *  "`status: draft` keeps this in the /scrape-contact queue" — an agent re-deriving a can-enter
 *  filter into prose because nothing surfaced it. */
function bindingsSection(entries) {
	const byCollection = new Map();
	for (const [rt, e] of entries) {
		if (!/^command-bindings\/.+\.command-binding\.yaml$/.test(rt)) continue;
		let d = {};
		try { d = load(e.bytes.toString('utf8')) ?? {}; } catch { continue; }
		const coll = String(d.collection ?? '').replace(/^collections\//, '');
		const cmd = String(d.command ?? '').replace(/^commands\//, '');
		if (!coll || !cmd) continue;
		const gate = [renderGate('enter', d['can-enter']), renderGate('exit', d['can-exit'])].filter(Boolean).join(' · ');
		if (!byCollection.has(coll)) byCollection.set(coll, []);
		byCollection.get(coll).push(`/${cmd}${gate ? ` (${gate})` : ''}`);
	}
	if (!byCollection.size) return [];
	const lines = ['', 'VERBS BOUND TO COLLECTIONS (`dt commands <collection>[/<id>]` answers per record):'];
	for (const coll of [...byCollection.keys()].sort()) lines.push(`- ${coll} — ${byCollection.get(coll).sort().join(' · ')}`);
	return lines;
}

/** `sourceLayout` describes what THIS workspace actually looks like — 'flat' (`<module>/skills/`),
 *  'nested' (the pre-2026-08-05 `<module>/system/skills/`), or 'mixed'. It is passed in rather than
 *  assumed because generated prose that contradicts the workspace is worse than no prose: this block
 *  is the first thing an agent session reads, and a workspace still on the old layout was being told
 *  to write somewhere it does not keep its sources.
 *
 *  `namespaces` is here for exactly the same reason, and it matters more. A reference is
 *  `<collection>/<id>`, and an id is ALSO a slash path — so in a workspace with declared namespaces an
 *  agent that splits `health/doctors/dana-levi` at the first slash reads a collection that does not
 *  exist. Naming the declared list is what makes the grammar decidable from this block alone, without
 *  the agent having to go read the manifest. A workspace with no namespaces gets no extra sentence. */
function orientationBlock(flavor, skillsIndex, sourceLayout = 'flat', namespaces = [], version = 'unknown', entries = new Map(), workspaceModule = '') {
	const sourcesLine = {
		flat: '`modules/<module>/<kind>/` — `collections/`, `skills/`, `agents/`, `commands/`,',
		nested: '`modules/<module>/system/<kind>/` — `collections/`, `skills/`, `agents/`, `commands/`,',
		mixed: '`modules/<module>/<kind>/`, or `<module>/system/<kind>/` where a module still nests it —\n`collections/`, `skills/`, `agents/`, `commands/`,',
	}[sourceLayout] ?? '`modules/<module>/<kind>/` — `collections/`, `skills/`, `agents/`, `commands/`,';
	const lines = [
		// PASSED IN, never hardcoded: this string used to say "v0.6" literally, which was correct for
		// exactly one minor release and then quietly wrong in every workspace it had been written into.
		// Passed rather than imported because compile.js already computes it and imports THIS module —
		// reaching back for `engineVersion` would close a cycle for the sake of one string.
		`this workspace is a typed record DSL operated by dreamteamer v${version} — collections are the`,
		'nouns. **read the `using-dreamteamer` skill before working with data or changing what the',
		'workspace keeps or does.** schemas (read): `.dreamteamer/collections/` (provenance:',
		'`.dreamteamer/manifest.yaml`). sources (write): ' + sourcesLine,
		'`command-bindings/`, `ui-views/`, `collection-templates/`',
		'(see manifest for channels). data: `data/`. records are `<id>.<suffix>.<ext>`',
		'files; ids are paths; references are `<collection>/<id>`. run `dreamteamer check` (`npm run',
		'check`) after bulk edits; run `dreamteamer compile` (`npm run compile`) after changing any',
		'source or installing modules.',
	];
	// ⚠ Only when the workspace HAS namespaces. Telling an agent about a feature this workspace does
	// not use is the same failure as telling it the wrong source layout — prose that contradicts the
	// workspace is worse than no prose.
	if (namespaces.length) {
		lines.push(
			`this workspace declares NAMESPACES: ${namespaces.map((n) => `\`${n}\``).join(', ')}. a collection`,
			'in one is named with its prefix (`health/doctors`), stores records under `data/<namespace>/`,',
			'and is referenced as `<namespace>/<collection>/<id>` — so split a reference at the end of the',
			'DECLARED prefix, not at the first slash. collections with no prefix are unaffected.',
		);
	}
	lines.push(...collectionsSection(buildCollectionsIndex(entries), buildModulesIndex(entries), workspaceModule));
	lines.push(...templatesSection(entries));
	lines.push(...bindingsSection(entries));
	// claude-code discovers skills natively (Skill tool) — an index in CLAUDE.md is pure
	// context bloat there. every other harness gets the trigger index + discovery pointers.
	if (flavor !== 'claude-code') {
		lines.push(
			'',
			"skills — reusable techniques, one folder per skill at `.agents/skills/` (canonical:",
			"`.dreamteamer/skills/`); each SKILL.md's description says when to load it. load",
			'the relevant skill BEFORE the task:',
			...skillsIndex.map((s) => `- \`${s.id}\` — ${s.desc}`),
			'',
			'agent personas live at `.dreamteamer/agents/*.agent.md`; commands at',
			'`.dreamteamer/commands/`, invoked as `/<name>` by the harness:',
			...buildCommandsIndex(entries).map((c) => `- \`/${c.id}\` — ${c.desc}`),
		);
	}
	return lines.join('\n');
}

// managed block in a USER-OWNED root file. content=null removes the block; a file left
// empty (or whitespace) after removal is deleted — we created it, we clean it up.
function writeBlock(root, filename, content) {
	const file = path.join(root, filename);
	const exists = fs.existsSync(file);
	if (content == null) {
		if (!exists) return;
		let text = fs.readFileSync(file, 'utf8');
		if (!text.includes(BEGIN)) return;
		text = text.replace(new RegExp(`\\n?\\n?${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}\\n?`), '\n');
		if (text.trim() === '') fs.rmSync(file);
		else fs.writeFileSync(file, text);
		return;
	}
	const block = `${BEGIN}\n${content}\n${END}`;
	let text = exists ? fs.readFileSync(file, 'utf8') : '';
	if (text.includes(BEGIN)) text = text.replace(new RegExp(`${escapeRe(BEGIN)}[\\s\\S]*?${escapeRe(END)}`), block);
	else text = (text.trimEnd() + '\n\n' + block + '\n').replace(/^\n+/, '');
	fs.writeFileSync(file, text);
}

export function stampMd(bytes) {
	const text = bytes.toString('utf8');
	return text.includes(STAMP) ? bytes : Buffer.from(text.trimEnd() + '\n\n' + STAMP + '\n');
}

// dreamteamer agent record -> claude-code subagent: `skills` is not a harness
// frontmatter key; translate it into a binding instruction in the body.
export function transformAgent(bytes) {
	const text = bytes.toString('utf8');
	const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(text);
	if (!m) return bytes;
	const doc = load(m[1]) ?? {};
	const body = text.slice(m[0].length);
	const skills = doc.skills ?? [];
	delete doc.skills;
	const skillLine = skills.length
		? `ALWAYS load these skills (Skill tool) before acting: ${skills.map((s) => String(s).replace(/^skills\//, '')).join(', ')}.\n\n`
		: '';
	return Buffer.from(`---\n${dump(doc)}---\n\n${skillLine}${body.trimStart()}`);
}

function escapeRe(s) {
	return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// depth-first removal of empty directories; returns true when `dir` itself was removed.
// dotfile-only dirs count as non-empty (never delete something we can't see into).
function pruneEmptyDirs(dir) {
	if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return false;
	for (const name of fs.readdirSync(dir)) {
		const p = path.join(dir, name);
		if (fs.statSync(p).isDirectory()) pruneEmptyDirs(p);
	}
	if (fs.readdirSync(dir).length === 0) {
		fs.rmdirSync(dir);
		return true;
	}
	return false;
}

function* walk(dir) {
	for (const name of fs.readdirSync(dir).sort()) {
		if (name.startsWith('.')) continue;
		const p = path.join(dir, name);
		if (fs.statSync(p).isDirectory()) yield* walk(p);
		else yield p;
	}
}
